name: Frontend Cloud Deployment

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-22.04

    steps:
    - name: Initial checkout
      uses: actions/checkout@v3

    - name: Set up npm
      uses: actions/setup-node@v3
      with:
        node-version: 16.13.0

    - name: Install dependencies
      run: npm install --force

    - name: Build app
      run: npm run build

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Execute script and store output
      id: get-ips
      run: |
        chmod +x ./script.sh
        ips=$(./script.sh)
        echo "$ips" > ips.txt
        cat ips.txt
      shell: bash

    - name: Loop through IP addresses and create tasks
      run: |
        ips=()
        while read -r ip; do
          ip=$(echo "$ip" | tr -d '\n')
          ips+=("$ip")
        done < ips.txt
        echo "The array of ips $ips"
        echo "${{ secrets.DEMO }}" > demo
        ls
        for ip in "${ips[@]}"; do
          ip=$(echo "$ip" | sed 's/"//g')
          echo "${{ secrets.AWS_HOST }}@$ip"
          scp -i demo -o StrictHostKeyChecking=no -r dist/devops-labs-frontend/ ${{ secrets.AWS_HOST }}@$ip:/frontend/
        done
